HW5/CampusApartments/CampusApartments/Models/Request.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CampusApartments.Models
{
    public class Request
    {
        [Key]
        public int RequestID { get; set; }

        [Required]
        [StringLength(25)]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [StringLength(25)]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }

        [Required]
        [StringLength(15)]
        [Display(Name = "Apartment Name")]
        public string ApartmentName { get; set; }

        [Required]
        [Display(Name = "Unit Number")]
        public int UnitNumber { get; set; }

        [Required]
        [StringLength(1000)]
        [Display(Name = "Maintenance Required")]
        public string MaintenanceRequired { get; set; }

        [Display(Name = "Time of Request")]
        public DateTime TimeOfRequest { get; set; }

        [Display(Name = "Permission to Enter?")]
        public bool Permission { get; set; }
    }
}

HW5/CampusApartments/CampusApartments/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CampusApartments.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

HW5/CampusApartments/CampusApartments/Controllers/RequestsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CampusApartments.DAL;
using CampusApartments.Models;

namespace CampusApartments.Controllers
{
    public class RequestsController : Controller
    {
        private RequestContext db = new RequestContext();

        // GET: Requests
        public ActionResult Index()
        {
            List<Request> list = db.Requests.ToList();
            var sorted = list.OrderBy(time => time.TimeOfRequest);
            return View(sorted);
        }

        // GET: Requests/Create
        public ActionResult Create()
        {
            @ViewBag.Time = DateTime.Now;
            return View();
        }

        // POST: Requests/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TimeOfRequest,FirstName,LastName,PhoneNumber,ApartmentName,UnitNumber,MaintenanceRequired,Permission")] Request request)
        {
            if (ModelState.IsValid)
            {
                db.Requests.Add(request);
                db.SaveChanges();
                return RedirectToAction("ThankYou");
            }

            return View(request);
        }

        //The view for after the submit works.
        public ActionResult ThankYou()
        {
            return View();
        }
    }
}

HW5/CampusApartments/CampusApartments/Views/Home/About.cshtml
@{
    ViewBag.Title = "Maintenance Request Form";
    ViewBag.About = "active";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>This will be the form page</p>

HW5/CampusApartments/CampusApartments/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
    ViewBag.Home = "active";
}

<div id="Intro" class="center">
    <h1 style="font:x-large">Campus Apartments</h1>
    <br />
    <p class="lead">
        The Campus Apartments is a wonderful complex to live it. We have cheap housing for students who
        need a place to live close to campus. We are only a 5 min walk away from the main building on campus.
        We make it easy to submit a maintenance request. 
    </p>
</div>

<div class="row">
    <div class="col-md-6">
        <div class="center">
            <h2>Renter's Corner</h2>
            <p>
                Hello Renters! The Campus Apartments are happy to have you living in them. We are happy to inform you that
                we have a spot for you to voice your complaints and submit maintenance requests from the comfort of your home.
                Once you have submitted the form one of our trusty workers will come by and fix the issue as soon as we can! Thank
                you for choosing Campus Apartments for your renting needs!
            </p>
            <p><a class="btn btn-default"@Html.ActionLink("Check out the Form", "Create", "Requests")</a></p>
        </div>
    </div>
    <div class="col-md-6">
        <div class="center">
            <h2>Manager's Corner</h2>
            <p>
                Hello Managers! Here is where you can find the report for the maintenance requests that have already been filled out.
                They include the phone numbers of the renter so you can contact them. Just make sure you know whether or not you have 
                permission to enter the unit before just going in (Don't worry, we made sure to include that in the report). Make sure
                you keep the people happy. Thank you for working for us!
            </p>
            <p><a class="btn btn-default"@Html.ActionLink("Maintenance Report", "Index", "Requests")</a></p>
        </div>
    </div>
</div>

HW5/CampusApartments/CampusApartments/Views/Requests/Create.cshtml
@model CampusApartments.Models.Request

@{
    ViewBag.MainR = "active";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <div class="center">
            <h2>Maintenance Request Form</h2>
        </div>
        <br />
        <div class="row">
            <div class="column" id="Side">
                <img src="~/Images/maintenance-request-page.jpg" style="width:100%">
                <img src="~/Images/maintenance_request_button.jpg" style="width:100%">
            </div>

            <div class="center">
                <div class="col-md-6">
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    @Html.HiddenFor(model => model.RequestID)
                    @Html.HiddenFor(model => model.TimeOfRequest, new { Value = @ViewBag.Time })

                    <div class="form-group">
                        @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-4", @style = "color: darkred;" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="center">
                            @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-4", @style = "color:darkred;" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div classs="center">
                            @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-4", @style = "color:darkred;" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="center">
                            @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.ApartmentName, htmlAttributes: new { @class = "control-label col-md-4", @style = "color:darkred;" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.ApartmentName, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="center">
                            @Html.ValidationMessageFor(model => model.ApartmentName, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.UnitNumber, htmlAttributes: new { @class = "control-label col-md-4", @style = "color:darkred;" })
                        <div class="col-md-8">
                            @Html.EditorFor(model => model.UnitNumber, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                        <div class="center">
                            @Html.ValidationMessageFor(model => model.UnitNumber, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-offset-4 col-md-8">
                            @Html.TextAreaFor(model => model.MaintenanceRequired, htmlAttributes: new { @class = "form-control", @rows = 10, @placeholder = "Explanation of request, maintenance required, or complaint. Please be specific." })
                        </div>
                        <div class="center">
                            @Html.ValidationMessageFor(model => model.MaintenanceRequired, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Permission, htmlAttributes: new { @class = "control-label col-md-6", @style = "color:darkred;" })
                        <div class="col-md-6">
                            @Html.CheckBoxFor(model => model.Permission)
                        </div>
                    </div>
                
                    @Html.ValueFor(model => model.TimeOfRequest)
                    <div class="form-group">
                        <div class="col-md-12">
                            <input type="submit" value="Submit Request" class="btn btn-default" />
                        </div>
                    </div>
                </div>

                <div class="column">    
                    <img src="~/Images/maintenance_request_button.jpg" style="width:100%">
                    <img src="~/Images/maintenance-request-page.jpg" style="width:100%">
                </div>

            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

HW5/CampusApartments/CampusApartments/Views/Requests/Index.cshtml
@model IEnumerable<CampusApartments.Models.Request>

@{
    ViewBag.Title = "Maintenance Requests Made";
    ViewBag.MainF = "active";
}

<div class="center">
    <h2>@ViewBag.Title</h2>
</div>

<table>
        <thead>
            <tr align="center">
                <th>
                    @Html.DisplayNameFor(model => model.TimeOfRequest)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FirstName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.LastName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PhoneNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ApartmentName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.UnitNumber)
                </th>
                <th align="center">
                    @Html.DisplayNameFor(model => model.MaintenanceRequired)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Permission)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr align="center">
                    <td>
                        @Html.DisplayFor(modelItem => item.TimeOfRequest)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.FirstName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.LastName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PhoneNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ApartmentName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.UnitNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MaintenanceRequired)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Permission)
                    </td>
                </tr>
            }
        </tbody>
</table>

HW5/CampusApartments/CampusApartments/Views/Requests/ThankYou.cshtml
@{
    ViewBag.Title = "Thank You";
    ViewBag.MainR = "active";
}

<div class="center" id="Intro">
    <h1>@ViewBag.Title</h1>
    <p>
        Your request has been submitted. We will be there in the next couple of days to fix the problem. If there is anything else
        you need from us please submit another form using the button below or give us a call at 1(800) 1-CAMPUS.
    </p>
</div>
<br />
<div class="center">
    <p><a class="btn btn-default" @Html.ActionLink("Submit Another", "Create", "Requests")</a></p>
</div>

HW5/CampusApartments/CampusApartments/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title Campus Apartments</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
              <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" id="navButtons">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Campus Apartments", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="@ViewBag.Home">@Html.ActionLink("Home Page", "Index", "Home")</li>
                    <li class="@ViewBag.MainR">@Html.ActionLink("Maintenance Request Form", "Create", "Requests")</li>
                    <li class="@ViewBag.MainF">@Html.ActionLink("Maintenance Requests Made", "Index", "Requests")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p style="font:medium Book Antiqua; color:darkred;">Campus Apartments</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>